/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nlcsn_graphcoloring;

/**
 *
 * @author Administrator
 */
public class HomeFrm extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrm
     */
    public HomeFrm() {
        initComponents();
        setLocationRelativeTo(null);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnMain = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        pnAvt = new javax.swing.JPanel();
        imgAvt = new javax.swing.JLabel();
        btnNhapThuCong = new javax.swing.JButton();
        btnNhapFile = new javax.swing.JButton();
        btnNhapRandom = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        btnGT_HD = new javax.swing.JButton();
        lbPhuongThucNhap = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang Chủ");

        jPanel1.setBackground(new java.awt.Color(4, 170, 109));

        pnMain.setBackground(new java.awt.Color(255, 255, 204));

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(4, 170, 109));
        lbTitle.setText("TÔ MÀU ĐỒ THỊ");

        pnAvt.setBackground(new java.awt.Color(4, 170, 109));

        imgAvt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Graph.png"))); // NOI18N

        javax.swing.GroupLayout pnAvtLayout = new javax.swing.GroupLayout(pnAvt);
        pnAvt.setLayout(pnAvtLayout);
        pnAvtLayout.setHorizontalGroup(
            pnAvtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAvtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgAvt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnAvtLayout.setVerticalGroup(
            pnAvtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAvtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgAvt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNhapThuCong.setBackground(new java.awt.Color(4, 170, 109));
        btnNhapThuCong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNhapThuCong.setForeground(new java.awt.Color(255, 255, 255));
        btnNhapThuCong.setText("Nhập Thủ Công");
        btnNhapThuCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapThuCongActionPerformed(evt);
            }
        });

        btnNhapFile.setBackground(new java.awt.Color(4, 170, 109));
        btnNhapFile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNhapFile.setForeground(new java.awt.Color(255, 255, 255));
        btnNhapFile.setText("Nhập Bằng File");
        btnNhapFile.setFocusPainted(false);
        btnNhapFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapFileActionPerformed(evt);
            }
        });

        btnNhapRandom.setBackground(new java.awt.Color(4, 170, 109));
        btnNhapRandom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNhapRandom.setForeground(new java.awt.Color(255, 255, 255));
        btnNhapRandom.setText("Nhập Random");
        btnNhapRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapRandomActionPerformed(evt);
            }
        });

        btnInfo.setBackground(new java.awt.Color(4, 170, 109));
        btnInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnInfo.setText("i");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        btnGT_HD.setBackground(new java.awt.Color(4, 170, 109));
        btnGT_HD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGT_HD.setForeground(new java.awt.Color(255, 255, 255));
        btnGT_HD.setText("?");
        btnGT_HD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGT_HDActionPerformed(evt);
            }
        });

        lbPhuongThucNhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPhuongThucNhap.setForeground(new java.awt.Color(4, 170, 109));
        lbPhuongThucNhap.setText("CHỌN PHƯƠNG THỨC NHẬP:");

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMainLayout.createSequentialGroup()
                        .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnMainLayout.createSequentialGroup()
                                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnNhapRandom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNhapFile))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnMainLayout.createSequentialGroup()
                                        .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnGT_HD, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnNhapThuCong)))
                            .addComponent(lbPhuongThucNhap)
                            .addComponent(pnAvt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMainLayout.createSequentialGroup()
                        .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnAvt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPhuongThucNhap)
                .addGap(18, 18, 18)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNhapFile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNhapThuCong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGT_HD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNhapRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhapFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapFileActionPerformed
        NhapFile nf = new NhapFile();
        nf.setVisible(true);
        nf.setLocationRelativeTo(null);  
        this.dispose();
    }//GEN-LAST:event_btnNhapFileActionPerformed

    private void btnGT_HDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGT_HDActionPerformed
        GioiThieu_HuongDan gthd = new GioiThieu_HuongDan();
        gthd.setVisible(true);
        gthd.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnGT_HDActionPerformed

    private void btnNhapRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapRandomActionPerformed
        nhapRandom rd = new nhapRandom();
        rd.setVisible(true);
        rd.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnNhapRandomActionPerformed

    private void btnNhapThuCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapThuCongActionPerformed
        nhapThuCong nc = new nhapThuCong();
        nc.setVisible(true);
        nc.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnNhapThuCongActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        MyInfo info = new MyInfo();
        info.setVisible(true);
        info.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGT_HD;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnNhapFile;
    private javax.swing.JButton btnNhapRandom;
    private javax.swing.JButton btnNhapThuCong;
    private javax.swing.JLabel imgAvt;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbPhuongThucNhap;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel pnAvt;
    private javax.swing.JPanel pnMain;
    // End of variables declaration//GEN-END:variables
}
