/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nlcsn_graphcoloring;

import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class NhapFile extends javax.swing.JFrame {

    /**
     * Creates new form NhapFile
     */
    public NhapFile() {
        initComponents();
        setLocationRelativeTo(null);
    }
    DoThi G = new DoThi();
    ToMau tomau = new ToMau();
    String tenFile = new String();
    String ketquaGreedy = new String();
    String ketquaWP = new String();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBorderMain = new javax.swing.JPanel();
        pnBackground = new javax.swing.JPanel();
        lbTitleNF = new javax.swing.JLabel();
        lnWP = new javax.swing.JLabel();
        lbKQGD = new javax.swing.JLabel();
        btnToMau = new javax.swing.JButton();
        lbTT2 = new javax.swing.JLabel();
        lbTT1 = new javax.swing.JLabel();
        lbTTTenFile = new javax.swing.JLabel();
        txtTenFile = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        pnBorderMaxtrix = new javax.swing.JPanel();
        scrpnMaTRan = new javax.swing.JScrollPane();
        txaMaTran = new javax.swing.JTextArea();
        pnBorderGreedy = new javax.swing.JPanel();
        scrpnGreedy = new javax.swing.JScrollPane();
        txaGreedy = new javax.swing.JTextArea();
        pnBorderWP = new javax.swing.JPanel();
        scrpnWP = new javax.swing.JScrollPane();
        txaWP = new javax.swing.JTextArea();
        btnXuatFile = new javax.swing.JButton();
        lbSaveName = new javax.swing.JLabel();
        txtSaveName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhập Dữ Liệu Từ File");

        pnBorderMain.setBackground(new java.awt.Color(4, 170, 109));

        pnBackground.setBackground(new java.awt.Color(255, 255, 204));

        lbTitleNF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTitleNF.setForeground(new java.awt.Color(4, 170, 109));
        lbTitleNF.setText("NHẬP DỮ LIỆU ĐỒ THỊ TỪ FILE");

        lnWP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lnWP.setForeground(new java.awt.Color(4, 170, 109));
        lnWP.setText("KẾT QUẢ WELSH POWELL:");

        lbKQGD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbKQGD.setForeground(new java.awt.Color(4, 170, 109));
        lbKQGD.setText("KẾT QUẢ GREEDY:");

        btnToMau.setBackground(new java.awt.Color(4, 170, 109));
        btnToMau.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnToMau.setForeground(new java.awt.Color(255, 255, 255));
        btnToMau.setText("Tiến Hành Tô Màu");
        btnToMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToMauActionPerformed(evt);
            }
        });

        lbTT2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTT2.setForeground(new java.awt.Color(4, 170, 109));
        lbTT2.setText("II. MA TRẬN:");

        lbTT1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTT1.setForeground(new java.awt.Color(4, 170, 109));
        lbTT1.setText("I. NHẬP TÊN FILE");

        lbTTTenFile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTTTenFile.setForeground(new java.awt.Color(4, 170, 109));
        lbTTTenFile.setText("Tên File:");

        txtTenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenFileActionPerformed(evt);
            }
        });

        btnOK.setBackground(new java.awt.Color(4, 170, 109));
        btnOK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOK.setForeground(new java.awt.Color(255, 255, 255));
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(4, 170, 109));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Quay Lại");
        btnBack.setFocusPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        pnBorderMaxtrix.setBackground(new java.awt.Color(4, 170, 109));

        txaMaTran.setColumns(20);
        txaMaTran.setRows(5);
        scrpnMaTRan.setViewportView(txaMaTran);

        javax.swing.GroupLayout pnBorderMaxtrixLayout = new javax.swing.GroupLayout(pnBorderMaxtrix);
        pnBorderMaxtrix.setLayout(pnBorderMaxtrixLayout);
        pnBorderMaxtrixLayout.setHorizontalGroup(
            pnBorderMaxtrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBorderMaxtrixLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrpnMaTRan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnBorderMaxtrixLayout.setVerticalGroup(
            pnBorderMaxtrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBorderMaxtrixLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrpnMaTRan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnBorderGreedy.setBackground(new java.awt.Color(4, 170, 109));

        txaGreedy.setColumns(20);
        txaGreedy.setRows(5);
        scrpnGreedy.setViewportView(txaGreedy);

        javax.swing.GroupLayout pnBorderGreedyLayout = new javax.swing.GroupLayout(pnBorderGreedy);
        pnBorderGreedy.setLayout(pnBorderGreedyLayout);
        pnBorderGreedyLayout.setHorizontalGroup(
            pnBorderGreedyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBorderGreedyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrpnGreedy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnBorderGreedyLayout.setVerticalGroup(
            pnBorderGreedyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBorderGreedyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrpnGreedy, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnBorderWP.setBackground(new java.awt.Color(4, 170, 109));

        txaWP.setColumns(20);
        txaWP.setRows(5);
        scrpnWP.setViewportView(txaWP);

        javax.swing.GroupLayout pnBorderWPLayout = new javax.swing.GroupLayout(pnBorderWP);
        pnBorderWP.setLayout(pnBorderWPLayout);
        pnBorderWPLayout.setHorizontalGroup(
            pnBorderWPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBorderWPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrpnWP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnBorderWPLayout.setVerticalGroup(
            pnBorderWPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBorderWPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrpnWP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnXuatFile.setBackground(new java.awt.Color(4, 170, 109));
        btnXuatFile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXuatFile.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatFile.setText("Tiến Hành Xuất Kết Quả Ra File");
        btnXuatFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatFileActionPerformed(evt);
            }
        });

        lbSaveName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbSaveName.setForeground(new java.awt.Color(4, 170, 109));
        lbSaveName.setText("Nhập Tên File Lưu Kết Quả:");

        javax.swing.GroupLayout pnBackgroundLayout = new javax.swing.GroupLayout(pnBackground);
        pnBackground.setLayout(pnBackgroundLayout);
        pnBackgroundLayout.setHorizontalGroup(
            pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBackgroundLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTT1)
                    .addComponent(btnBack)
                    .addGroup(pnBackgroundLayout.createSequentialGroup()
                        .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnToMau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbTT2)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBackgroundLayout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(lbTTTenFile)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtTenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnOK)))
                            .addComponent(pnBorderMaxtrix, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTitleNF)
                            .addGroup(pnBackgroundLayout.createSequentialGroup()
                                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbKQGD)
                                    .addComponent(pnBorderGreedy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnBackgroundLayout.createSequentialGroup()
                                        .addComponent(lbSaveName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSaveName)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lnWP)
                                    .addComponent(pnBorderWP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnXuatFile, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pnBackgroundLayout.setVerticalGroup(
            pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBackgroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTitleNF))
                .addGap(28, 28, 28)
                .addComponent(lbTT1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTTTenFile)
                    .addComponent(btnOK))
                .addGap(24, 24, 24)
                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTT2)
                    .addComponent(lbKQGD)
                    .addComponent(lnWP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnBorderWP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnBorderGreedy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnBorderMaxtrix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnToMau)
                    .addComponent(btnXuatFile)
                    .addComponent(lbSaveName)
                    .addComponent(txtSaveName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnBorderMainLayout = new javax.swing.GroupLayout(pnBorderMain);
        pnBorderMain.setLayout(pnBorderMainLayout);
        pnBorderMainLayout.setHorizontalGroup(
            pnBorderMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBorderMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnBorderMainLayout.setVerticalGroup(
            pnBorderMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBorderMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBorderMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBorderMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenFileActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        HomeFrm home = new HomeFrm();
        home.setVisible(true);
        home.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        tenFile = txtTenFile.getText();
        tomau = new ToMau(G);
        try {
            ketquaGreedy = tomau.thucHien(G, tenFile);
            ketquaWP = tomau.thucHienWP(G, tenFile);
            if(ketquaGreedy == "")
                JOptionPane.showConfirmDialog(this, "Không tìm thấy file", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NhapFile.class.getName()).log(Level.SEVERE, null, ex);
        }
        txaMaTran.setText(G.in(G));
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnToMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToMauActionPerformed
        txaWP.setText(ketquaWP);
        txaGreedy.setText(ketquaGreedy);
    }//GEN-LAST:event_btnToMauActionPerformed

    private void btnXuatFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatFileActionPerformed
        String matrix = txaMaTran.getText();
        String kqgd = txaGreedy.getText();
        String kqwp = txaWP.getText();
        String tenSave = txtSaveName.getText();
        try {
            FileWriter fw = new FileWriter(tenSave);
            fw.write("Ma trận kề đỉnh - đỉnh: \n"
                    + "- - - - - - - - - - - - - - - - - - - -\n"
                    + matrix 
                    + "- - - - - - - - - - - - - - - - - - - -\n\n" 
                    + "Kết quả Thuật toán Greedy: \n"
                    + "- - - - - - - - - - - - - - - - - - - -\n"
                    + kqgd 
                    + "- - - - - - - - - - - - - - - - - - - -\n\n"
                    + "Kết quả Thuật toán Welsh Powell: \n"
                    + "- - - - - - - - - - - - - - - - - - - -\n"
                    + kqwp
                    + "- - - - - - - - - - - - - - - - - - - -\n");
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(NhapFile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXuatFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NhapFile nf = new NhapFile();
                nf.setVisible(true);
                nf.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnToMau;
    private javax.swing.JButton btnXuatFile;
    private javax.swing.JLabel lbKQGD;
    private javax.swing.JLabel lbSaveName;
    private javax.swing.JLabel lbTT1;
    private javax.swing.JLabel lbTT2;
    private javax.swing.JLabel lbTTTenFile;
    private javax.swing.JLabel lbTitleNF;
    private javax.swing.JLabel lnWP;
    private javax.swing.JPanel pnBackground;
    private javax.swing.JPanel pnBorderGreedy;
    private javax.swing.JPanel pnBorderMain;
    private javax.swing.JPanel pnBorderMaxtrix;
    private javax.swing.JPanel pnBorderWP;
    private javax.swing.JScrollPane scrpnGreedy;
    private javax.swing.JScrollPane scrpnMaTRan;
    private javax.swing.JScrollPane scrpnWP;
    private javax.swing.JTextArea txaGreedy;
    private javax.swing.JTextArea txaMaTran;
    private javax.swing.JTextArea txaWP;
    private javax.swing.JTextField txtSaveName;
    private javax.swing.JTextField txtTenFile;
    // End of variables declaration//GEN-END:variables
}
