/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nlcsn_graphcoloring;

import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class nhapRandom extends javax.swing.JFrame {

    /**
     * Creates new form nhapRandom
     */
    public nhapRandom() {
        initComponents();
        setLocationRelativeTo(null);
    }
    DoThi G = new DoThi();
    public int n,m;
    ToMau tomau = new ToMau();
    String ketquaThamLam = new String();
    String ketquaWP = new String();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgBorder = new javax.swing.JPanel();
        bgColor = new javax.swing.JPanel();
        lbKQWP = new javax.swing.JLabel();
        lbTittle = new javax.swing.JLabel();
        lbKQGreedy = new javax.swing.JLabel();
        lbMaTran = new javax.swing.JLabel();
        btnToMau = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        bgBorderMaTran = new javax.swing.JPanel();
        scrpnMaTran = new javax.swing.JScrollPane();
        txaMaTran = new javax.swing.JTextArea();
        bgBorderGD = new javax.swing.JPanel();
        scrpnGreedy = new javax.swing.JScrollPane();
        txaGreedy = new javax.swing.JTextArea();
        bgKQWP = new javax.swing.JPanel();
        scrpnWP = new javax.swing.JScrollPane();
        txaWP = new javax.swing.JTextArea();
        lbDinhCung = new javax.swing.JLabel();
        lbDinh = new javax.swing.JLabel();
        txtDinh = new javax.swing.JTextField();
        lbCung = new javax.swing.JLabel();
        txtCung = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        btnXuatFile = new javax.swing.JButton();
        lbSaveName = new javax.swing.JLabel();
        txtSaveName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhập Dữ Liệu Random");

        bgBorder.setBackground(new java.awt.Color(4, 170, 109));

        bgColor.setBackground(new java.awt.Color(255, 255, 204));

        lbKQWP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbKQWP.setForeground(new java.awt.Color(4, 170, 109));
        lbKQWP.setText("KẾT QUẢ WELSH POWELL:");

        lbTittle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTittle.setForeground(new java.awt.Color(4, 170, 109));
        lbTittle.setText("NHẬP DỮ LIỆU ĐỒ THỊ RANDOM");

        lbKQGreedy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbKQGreedy.setForeground(new java.awt.Color(4, 170, 109));
        lbKQGreedy.setText("KẾT QUẢ GREEDY:");

        lbMaTran.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbMaTran.setForeground(new java.awt.Color(4, 170, 109));
        lbMaTran.setText("II. MA TRẬN:");

        btnToMau.setBackground(new java.awt.Color(4, 170, 109));
        btnToMau.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnToMau.setForeground(new java.awt.Color(255, 255, 255));
        btnToMau.setText("Tiến Hành Tô Màu");
        btnToMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToMauActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(4, 170, 109));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Quay Lại");
        btnBack.setFocusPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        bgBorderMaTran.setBackground(new java.awt.Color(4, 170, 109));

        txaMaTran.setColumns(20);
        txaMaTran.setRows(5);
        scrpnMaTran.setViewportView(txaMaTran);

        javax.swing.GroupLayout bgBorderMaTranLayout = new javax.swing.GroupLayout(bgBorderMaTran);
        bgBorderMaTran.setLayout(bgBorderMaTranLayout);
        bgBorderMaTranLayout.setHorizontalGroup(
            bgBorderMaTranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBorderMaTranLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrpnMaTran)
                .addContainerGap())
        );
        bgBorderMaTranLayout.setVerticalGroup(
            bgBorderMaTranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBorderMaTranLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrpnMaTran, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bgBorderGD.setBackground(new java.awt.Color(4, 170, 109));

        txaGreedy.setColumns(20);
        txaGreedy.setRows(5);
        scrpnGreedy.setViewportView(txaGreedy);

        javax.swing.GroupLayout bgBorderGDLayout = new javax.swing.GroupLayout(bgBorderGD);
        bgBorderGD.setLayout(bgBorderGDLayout);
        bgBorderGDLayout.setHorizontalGroup(
            bgBorderGDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBorderGDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrpnGreedy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgBorderGDLayout.setVerticalGroup(
            bgBorderGDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgBorderGDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrpnGreedy, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bgKQWP.setBackground(new java.awt.Color(4, 170, 109));

        txaWP.setColumns(20);
        txaWP.setRows(5);
        scrpnWP.setViewportView(txaWP);

        javax.swing.GroupLayout bgKQWPLayout = new javax.swing.GroupLayout(bgKQWP);
        bgKQWP.setLayout(bgKQWPLayout);
        bgKQWPLayout.setHorizontalGroup(
            bgKQWPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgKQWPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrpnWP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgKQWPLayout.setVerticalGroup(
            bgKQWPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgKQWPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrpnWP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbDinhCung.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDinhCung.setForeground(new java.awt.Color(4, 170, 109));
        lbDinhCung.setText("I. NHẬP ĐỈNH VÀ CUNG:");

        lbDinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDinh.setForeground(new java.awt.Color(4, 170, 109));
        lbDinh.setText("1. Nhập Số Đỉnh:");

        lbCung.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCung.setForeground(new java.awt.Color(4, 170, 109));
        lbCung.setText("2. Nhập Số Cung:");

        btnOk.setBackground(new java.awt.Color(4, 170, 109));
        btnOk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOk.setForeground(new java.awt.Color(255, 255, 255));
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnXuatFile.setBackground(new java.awt.Color(4, 170, 109));
        btnXuatFile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXuatFile.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatFile.setText("Tiến Hành Xuất Kết Quả Ra File");
        btnXuatFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatFileActionPerformed(evt);
            }
        });

        lbSaveName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbSaveName.setForeground(new java.awt.Color(4, 170, 109));
        lbSaveName.setText("Nhập Tên File Lưu Kết Quả:");

        javax.swing.GroupLayout bgColorLayout = new javax.swing.GroupLayout(bgColor);
        bgColor.setLayout(bgColorLayout);
        bgColorLayout.setHorizontalGroup(
            bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgColorLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDinhCung)
                    .addGroup(bgColorLayout.createSequentialGroup()
                        .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbMaTran)
                            .addComponent(btnBack)
                            .addComponent(bgBorderMaTran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnToMau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTittle)
                            .addGroup(bgColorLayout.createSequentialGroup()
                                .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bgBorderGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbKQGreedy)
                                    .addGroup(bgColorLayout.createSequentialGroup()
                                        .addComponent(lbSaveName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSaveName)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bgKQWP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbKQWP)
                                    .addComponent(btnXuatFile, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(bgColorLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDinh)
                            .addComponent(lbCung))
                        .addGap(28, 28, 28)
                        .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(txtDinh)
                            .addComponent(txtCung))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        bgColorLayout.setVerticalGroup(
            bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgColorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTittle))
                .addGap(36, 36, 36)
                .addComponent(lbDinhCung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDinh)
                    .addComponent(txtDinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCung)
                    .addComponent(txtCung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOk)
                .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgColorLayout.createSequentialGroup()
                        .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMaTran)
                            .addComponent(lbKQGreedy)
                            .addComponent(lbKQWP))
                        .addGap(4, 4, 4)
                        .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bgBorderGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bgKQWP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgColorLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(bgBorderMaTran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnToMau)
                    .addComponent(btnXuatFile)
                    .addComponent(lbSaveName)
                    .addComponent(txtSaveName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgBorderLayout = new javax.swing.GroupLayout(bgBorder);
        bgBorder.setLayout(bgBorderLayout);
        bgBorderLayout.setHorizontalGroup(
            bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBorderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bgColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgBorderLayout.setVerticalGroup(
            bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBorderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bgColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        HomeFrm home = new HomeFrm();
        home.setVisible(true);
        home.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnToMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToMauActionPerformed
        txaWP.setText(ketquaWP);
        txaGreedy.setText(ketquaThamLam);
        System.out.println(G.in(G));
    }//GEN-LAST:event_btnToMauActionPerformed

    private void btnXuatFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatFileActionPerformed
        String matrix = txaMaTran.getText();
        String kqgd = txaGreedy.getText();
        String kqwp = txaWP.getText();
        String tenSave = txtSaveName.getText();
        try {
            FileWriter fw = new FileWriter(tenSave);
            fw.write("Ma trận kề đỉnh - đỉnh: \n"
                    + "- - - - - - - - - - - - - - - - - - - -\n"
                    + matrix 
                    + "- - - - - - - - - - - - - - - - - - - -\n\n" 
                    + "Kết quả Thuật toán Greedy: \n"
                    + "- - - - - - - - - - - - - - - - - - - -\n"
                    + kqgd 
                    + "- - - - - - - - - - - - - - - - - - - -\n\n"
                    + "Kết quả Thuật toán Welsh Powell: \n"
                    + "- - - - - - - - - - - - - - - - - - - -\n"
                    + kqwp
                    + "- - - - - - - - - - - - - - - - - - - -\n");
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(NhapFile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXuatFileActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        n = Integer.parseInt(txtDinh.getText());
        m = Integer.parseInt(txtCung.getText());
        if ( n*m <= 0) {
            JOptionPane.showMessageDialog(this, "Nhập số đỉnh và cung lớn hơn 0", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        ketquaThamLam = tomau.thucHien(G, n, m);
        ketquaWP = tomau.thucHienWP(G, n, m);
        txaMaTran.setText(G.in(G));
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nhapRandom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nhapRandom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nhapRandom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nhapRandom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nhapRandom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgBorder;
    private javax.swing.JPanel bgBorderGD;
    private javax.swing.JPanel bgBorderMaTran;
    private javax.swing.JPanel bgColor;
    private javax.swing.JPanel bgKQWP;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnToMau;
    private javax.swing.JButton btnXuatFile;
    private javax.swing.JLabel lbCung;
    private javax.swing.JLabel lbDinh;
    private javax.swing.JLabel lbDinhCung;
    private javax.swing.JLabel lbKQGreedy;
    private javax.swing.JLabel lbKQWP;
    private javax.swing.JLabel lbMaTran;
    private javax.swing.JLabel lbSaveName;
    private javax.swing.JLabel lbTittle;
    private javax.swing.JScrollPane scrpnGreedy;
    private javax.swing.JScrollPane scrpnMaTran;
    private javax.swing.JScrollPane scrpnWP;
    private javax.swing.JTextArea txaGreedy;
    private javax.swing.JTextArea txaMaTran;
    private javax.swing.JTextArea txaWP;
    private javax.swing.JTextField txtCung;
    private javax.swing.JTextField txtDinh;
    private javax.swing.JTextField txtSaveName;
    // End of variables declaration//GEN-END:variables
}
