/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nlcsn_graphcoloring;

import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class nhapThuCong extends javax.swing.JFrame {

    /**
     * Creates new form nhapThuCong
     */
    public nhapThuCong() {
        initComponents();
        setLocationRelativeTo(null);
        moDel = (DefaultTableModel) tblCDD.getModel();
    }
    DoThi G =  new DoThi();
    private int n, m, u, v, i=1;
    ToMau toMau = new ToMau();
    String ketquaGreedy = new String();
    String ketquaWP = new String();
    DefaultTableModel moDel = new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        bgColor = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        lbTittleI = new javax.swing.JLabel();
        lbDinh = new javax.swing.JLabel();
        txtDinh = new javax.swing.JTextField();
        lbCung = new javax.swing.JLabel();
        txtCung = new javax.swing.JTextField();
        btnKhoiTao = new javax.swing.JButton();
        lnTittleII = new javax.swing.JLabel();
        lbDinh1 = new javax.swing.JLabel();
        txtDinh1 = new javax.swing.JTextField();
        lbDinh2 = new javax.swing.JLabel();
        txtDinh2 = new javax.swing.JTextField();
        btnThemCung = new javax.swing.JButton();
        lnTittle = new javax.swing.JLabel();
        lbMaTran = new javax.swing.JLabel();
        btnToMau = new javax.swing.JButton();
        bgBorderMaTran = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMaTran = new javax.swing.JTextArea();
        lnKQGreedy = new javax.swing.JLabel();
        bgBorderGD = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaGreedy = new javax.swing.JTextArea();
        lbKQWP = new javax.swing.JLabel();
        bgBorderWP = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaWP = new javax.swing.JTextArea();
        lbBangDS = new javax.swing.JLabel();
        bgBorderBang = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblCDD = new javax.swing.JTable();
        btnXuatFile = new javax.swing.JButton();
        lbSaveName = new javax.swing.JLabel();
        txtSaveName = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhập Dữ Liệu Thủ Công");

        jPanel1.setBackground(new java.awt.Color(4, 170, 109));

        bgColor.setBackground(new java.awt.Color(255, 255, 204));

        btnBack.setBackground(new java.awt.Color(4, 170, 109));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Quay Lại");
        btnBack.setFocusPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lbTittleI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTittleI.setForeground(new java.awt.Color(4, 170, 109));
        lbTittleI.setText("I. NHẬP SỐ ĐỈNH VÀ SỐ CUNG:");

        lbDinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDinh.setForeground(new java.awt.Color(4, 170, 109));
        lbDinh.setText("1. Nhập Số Đỉnh:");

        lbCung.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCung.setForeground(new java.awt.Color(4, 170, 109));
        lbCung.setText("2. Nhập Số Cung:");

        btnKhoiTao.setBackground(new java.awt.Color(4, 170, 109));
        btnKhoiTao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKhoiTao.setForeground(new java.awt.Color(255, 255, 255));
        btnKhoiTao.setText("Khởi Tạo");
        btnKhoiTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoiTaoActionPerformed(evt);
            }
        });

        lnTittleII.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lnTittleII.setForeground(new java.awt.Color(4, 170, 109));
        lnTittleII.setText("II. NHẬP DANH SÁCH CUNG (LẦN LƯỢT):");

        lbDinh1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDinh1.setForeground(new java.awt.Color(4, 170, 109));
        lbDinh1.setText("3. Nhập Đỉnh 1:");

        lbDinh2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDinh2.setForeground(new java.awt.Color(4, 170, 109));
        lbDinh2.setText("4. Nhập Đỉnh 2:");

        btnThemCung.setBackground(new java.awt.Color(4, 170, 109));
        btnThemCung.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemCung.setForeground(new java.awt.Color(255, 255, 255));
        btnThemCung.setText("Thêm Cung");
        btnThemCung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCungActionPerformed(evt);
            }
        });

        lnTittle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lnTittle.setForeground(new java.awt.Color(4, 170, 109));
        lnTittle.setText("NHẬP DỮ LIỆU ĐỒ THỊ THỦ CÔNG (NHẬP TỪNG CUNG)");

        lbMaTran.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMaTran.setForeground(new java.awt.Color(4, 170, 109));
        lbMaTran.setText("III. MA TRẬN:");

        btnToMau.setBackground(new java.awt.Color(4, 170, 109));
        btnToMau.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnToMau.setForeground(new java.awt.Color(255, 255, 255));
        btnToMau.setText("Tiến Hành Tô Màu");
        btnToMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToMauActionPerformed(evt);
            }
        });

        bgBorderMaTran.setBackground(new java.awt.Color(4, 170, 109));

        txaMaTran.setColumns(20);
        txaMaTran.setRows(5);
        jScrollPane1.setViewportView(txaMaTran);

        javax.swing.GroupLayout bgBorderMaTranLayout = new javax.swing.GroupLayout(bgBorderMaTran);
        bgBorderMaTran.setLayout(bgBorderMaTranLayout);
        bgBorderMaTranLayout.setHorizontalGroup(
            bgBorderMaTranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBorderMaTranLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        bgBorderMaTranLayout.setVerticalGroup(
            bgBorderMaTranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBorderMaTranLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lnKQGreedy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lnKQGreedy.setForeground(new java.awt.Color(4, 170, 109));
        lnKQGreedy.setText("KẾT QUẢ GREEDY:");

        bgBorderGD.setBackground(new java.awt.Color(4, 170, 109));

        txaGreedy.setColumns(20);
        txaGreedy.setRows(5);
        jScrollPane2.setViewportView(txaGreedy);

        javax.swing.GroupLayout bgBorderGDLayout = new javax.swing.GroupLayout(bgBorderGD);
        bgBorderGD.setLayout(bgBorderGDLayout);
        bgBorderGDLayout.setHorizontalGroup(
            bgBorderGDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBorderGDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgBorderGDLayout.setVerticalGroup(
            bgBorderGDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBorderGDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbKQWP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbKQWP.setForeground(new java.awt.Color(4, 170, 109));
        lbKQWP.setText("KẾT QUẢ WELSH POWELL:");

        bgBorderWP.setBackground(new java.awt.Color(4, 170, 109));

        txaWP.setColumns(20);
        txaWP.setRows(5);
        jScrollPane3.setViewportView(txaWP);

        javax.swing.GroupLayout bgBorderWPLayout = new javax.swing.GroupLayout(bgBorderWP);
        bgBorderWP.setLayout(bgBorderWPLayout);
        bgBorderWPLayout.setHorizontalGroup(
            bgBorderWPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBorderWPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgBorderWPLayout.setVerticalGroup(
            bgBorderWPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBorderWPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbBangDS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbBangDS.setForeground(new java.awt.Color(4, 170, 109));
        lbBangDS.setText("*BẢNG DANH SÁCH CUNG ĐÃ THÊM:");

        bgBorderBang.setBackground(new java.awt.Color(4, 170, 109));

        tblCDD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cung", "Đỉnh", "Đỉnh"
            }
        ));
        jScrollPane5.setViewportView(tblCDD);

        javax.swing.GroupLayout bgBorderBangLayout = new javax.swing.GroupLayout(bgBorderBang);
        bgBorderBang.setLayout(bgBorderBangLayout);
        bgBorderBangLayout.setHorizontalGroup(
            bgBorderBangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBorderBangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );
        bgBorderBangLayout.setVerticalGroup(
            bgBorderBangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBorderBangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnXuatFile.setBackground(new java.awt.Color(4, 170, 109));
        btnXuatFile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXuatFile.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatFile.setText("Tiến Hành Xuất Kết Quả Ra File");
        btnXuatFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatFileActionPerformed(evt);
            }
        });

        lbSaveName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbSaveName.setForeground(new java.awt.Color(4, 170, 109));
        lbSaveName.setText("Nhập Tên File Lưu Kết Quả:");

        javax.swing.GroupLayout bgColorLayout = new javax.swing.GroupLayout(bgColor);
        bgColor.setLayout(bgColorLayout);
        bgColorLayout.setHorizontalGroup(
            bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgColorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgColorLayout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(96, 96, 96)
                        .addComponent(lnTittle))
                    .addGroup(bgColorLayout.createSequentialGroup()
                        .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTittleI)
                            .addGroup(bgColorLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(bgColorLayout.createSequentialGroup()
                                        .addComponent(lbDinh)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtDinh, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(bgColorLayout.createSequentialGroup()
                                        .addComponent(lbCung)
                                        .addGap(18, 18, 18)
                                        .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnKhoiTao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtCung, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(18, 18, 18)
                        .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lnTittleII)
                            .addGroup(bgColorLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbDinh1)
                                    .addComponent(lbDinh2))
                                .addGap(39, 39, 39)
                                .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnThemCung, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDinh2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgColorLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lbBangDS))
                            .addGroup(bgColorLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(bgBorderBang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(bgColorLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbMaTran)
                            .addComponent(bgBorderMaTran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnToMau, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lnKQGreedy)
                            .addComponent(bgBorderGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bgColorLayout.createSequentialGroup()
                                .addComponent(lbSaveName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSaveName)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXuatFile, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bgBorderWP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbKQWP))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        bgColorLayout.setVerticalGroup(
            bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgColorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnTittle))
                .addGap(45, 45, 45)
                .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTittleI)
                    .addComponent(lnTittleII)
                    .addComponent(lbBangDS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgColorLayout.createSequentialGroup()
                        .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDinh)
                            .addComponent(txtDinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCung)
                            .addComponent(txtCung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKhoiTao))
                    .addGroup(bgColorLayout.createSequentialGroup()
                        .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDinh1)
                            .addComponent(txtDinh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDinh2)
                            .addComponent(txtDinh2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThemCung))
                    .addComponent(bgBorderBang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgColorLayout.createSequentialGroup()
                            .addComponent(lbMaTran)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bgBorderMaTran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgColorLayout.createSequentialGroup()
                            .addComponent(lnKQGreedy)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bgBorderGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgColorLayout.createSequentialGroup()
                        .addComponent(lbKQWP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bgBorderWP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnToMau)
                    .addComponent(btnXuatFile)
                    .addComponent(lbSaveName)
                    .addComponent(txtSaveName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bgColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bgColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        HomeFrm tc = new HomeFrm();
        tc.setVisible(true);
        tc.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnKhoiTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoiTaoActionPerformed
        n = Integer.parseInt(txtDinh.getText());
        m = Integer.parseInt(txtCung.getText());
        if ( n*m <= 0) {
            JOptionPane.showMessageDialog(this, "Nhập số đỉnh và cung lớn hơn 0", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        G.ktaoDoThi(G, n);
        txaMaTran.setText(G.in(G));
    }//GEN-LAST:event_btnKhoiTaoActionPerformed

    private void btnThemCungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCungActionPerformed
        u = Integer.parseInt(txtDinh1.getText());
        v = Integer.parseInt(txtDinh2.getText());        
        if (u == v) {
            JOptionPane.showMessageDialog(this, "Hai đỉnh phải khác nhau", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else{
            if(i <= m){
                if(!G.kiemTraKe(G, u, v)){
                    G.themCung(G, u, v);
                    txaMaTran.setText(G.in(G));
                    moDel.addRow(new Object[]{
                    i++,u,v
                    });     
                }
                else   
                    JOptionPane.showMessageDialog(this, "Cung đã tồn tại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnThemCungActionPerformed

    private void btnToMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToMauActionPerformed
        ketquaGreedy = toMau.thucHien(G, n);
        ketquaWP = toMau.thucHienWP(G, n);
        txaWP.setText(ketquaWP);
        txaGreedy.setText(ketquaGreedy);
    }//GEN-LAST:event_btnToMauActionPerformed

    private void btnXuatFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatFileActionPerformed
        String matrix = txaMaTran.getText();
        String kqgd = txaGreedy.getText();
        String kqwp = txaWP.getText();
        String tenSave = txtSaveName.getText();
        try {
            FileWriter fw = new FileWriter(tenSave);
            fw.write("Ma trận kề đỉnh - đỉnh: \n"
                    + "- - - - - - - - - - - - - - - - - - - -\n"
                    + matrix 
                    + "- - - - - - - - - - - - - - - - - - - -\n\n" 
                    + "Kết quả Thuật toán Greedy: \n"
                    + "- - - - - - - - - - - - - - - - - - - -\n"
                    + kqgd 
                    + "- - - - - - - - - - - - - - - - - - - -\n\n"
                    + "Kết quả Thuật toán Welsh Powell: \n"
                    + "- - - - - - - - - - - - - - - - - - - -\n"
                    + kqwp
                    + "- - - - - - - - - - - - - - - - - - - -\n");
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(NhapFile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXuatFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nhapThuCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nhapThuCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nhapThuCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nhapThuCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nhapThuCong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgBorderBang;
    private javax.swing.JPanel bgBorderGD;
    private javax.swing.JPanel bgBorderMaTran;
    private javax.swing.JPanel bgBorderWP;
    private javax.swing.JPanel bgColor;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnKhoiTao;
    private javax.swing.JButton btnThemCung;
    private javax.swing.JButton btnToMau;
    private javax.swing.JButton btnXuatFile;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbBangDS;
    private javax.swing.JLabel lbCung;
    private javax.swing.JLabel lbDinh;
    private javax.swing.JLabel lbDinh1;
    private javax.swing.JLabel lbDinh2;
    private javax.swing.JLabel lbKQWP;
    private javax.swing.JLabel lbMaTran;
    private javax.swing.JLabel lbSaveName;
    private javax.swing.JLabel lbTittleI;
    private javax.swing.JLabel lnKQGreedy;
    private javax.swing.JLabel lnTittle;
    private javax.swing.JLabel lnTittleII;
    private javax.swing.JTable tblCDD;
    private javax.swing.JTextArea txaGreedy;
    private javax.swing.JTextArea txaMaTran;
    private javax.swing.JTextArea txaWP;
    private javax.swing.JTextField txtCung;
    private javax.swing.JTextField txtDinh;
    private javax.swing.JTextField txtDinh1;
    private javax.swing.JTextField txtDinh2;
    private javax.swing.JTextField txtSaveName;
    // End of variables declaration//GEN-END:variables
}
